In [6]:
import numpy as np
 
import pandas as pd
 
import matplotlib.pyplot as plt
 
import statsmodels.api as sm
import os
import glob

In [7]:
mergedTrialData_df = pd.read_csv("mergedTrialData.csv")
demographics_df = pd.read_csv("demographic.csv")

In [8]:
mergedTrialData_averaged_df = mergedTrialData_df.groupby('subject').mean()

In [9]:
mergedTrialData_averaged_df.merge(demographics_df, on='subject').rename(columns={' group': 'group'})

,subject,trial,condition,ITI,rejected,Fz_N100,FCz_N100,Cz_N100,FC3_N100,FC4_N100,...,FC3_B1,FC4_B1,C3_B1,C4_B1,CP3_B1,CP4_B1,group,gender,age,education
0,1,50.171141,2.000000,2825.814358,0.030201,-3.758078,-3.709469,-3.430479,-3.159399,-3.759882,...,1.770834,0.828906,1.753613,0.670578,1.435104,0.932307,0,M,44,16.0
1,2,50.171141,2.000000,2350.668702,0.000000,-2.477591,-2.633028,-2.263567,-1.902506,-1.888696,...,0.285030,0.688827,0.346570,-0.044879,-0.074469,0.165761,0,M,39,17.0
2,3,50.171141,2.000000,1794.028080,0.036913,-3.714925,-4.351427,-4.252977,-2.789237,-2.799512,...,0.661526,1.149944,-0.206321,-0.355422,-1.118638,-0.935494,0,M,53,18.0
3,4,50.003367,2.003367,2227.263372,0.030303,-4.717606,-4.224721,-3.074499,-2.741106,-3.452926,...,2.255097,1.417232,2.326886,1.577574,2.142686,1.302185,0,M,52,15.0
4,5,50.334448,2.000000,2515.888944,0.030100,-3.637179,-3.890643,-3.407677,-3.308248,-3.304539,...,2.975226,2.480377,2.418446,2.309906,1.685082,1.826066,0,M,41,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,77,50.171141,2.000000,3892.965445,0.067114,-1.166457,-0.952511,-0.151696,-0.352796,-0.860758,...,1.202070,0.488183,0.883494,0.244616,0.590810,-0.216080,1,M,28,13.0
77,78,50.010101,2.000000,3013.303182,0.037037,-3.221408,-2.387152,-2.381237,-1.252020,-3.127319,...,-0.089042,0.422882,-0.175286,0.096642,0.033592,0.024343,1,F,32,16.0
78,79,50.171141,2.000000,2442.892618,0.010067,-4.028807,-4.121220,-3.302542,-2.934670,-3.537007,...,1.374701,0.805522,2.333357,1.721417,1.437692,1.282188,1,M,37,16.0
79,80,50.171141,2.000000,1385.126462,0.053691,-2.361078,-2.142041,-1.667392,-1.908183,-1.453830,...,-0.161741,0.115978,-0.455912,0.037916,-0.876926,-0.366361,1,M,33,13.0
80,81,50.171141,2.000000,1800.367456,0.020134,-1.421697,-0.641675,0.246824,-0.439731,-0.541009,...,-0.249396,-0.242708,-0.347973,-0.434805,0.063599,-0.518138,1,M,56,13.0

In [12]:
All_data= mergedTrialData_averaged_df.merge(demographics_df, on='subject').rename(columns={' group': 'group'})

In [14]:
All_data.head()

,subject,trial,condition,ITI,rejected,Fz_N100,FCz_N100,Cz_N100,FC3_N100,FC4_N100,...,FC3_B1,FC4_B1,C3_B1,C4_B1,CP3_B1,CP4_B1,group,gender,age,education
0,1,50.171141,2.000000,2825.814358,0.030201,-3.758078,-3.709469,-3.430479,-3.159399,-3.759882,...,1.770834,0.828906,1.753613,0.670578,1.435104,0.932307,0,M,44,16.0
1,2,50.171141,2.000000,2350.668702,0.000000,-2.477591,-2.633028,-2.263567,-1.902506,-1.888696,...,0.285030,0.688827,0.346570,-0.044879,-0.074469,0.165761,0,M,39,17.0
2,3,50.171141,2.000000,1794.028080,0.036913,-3.714925,-4.351427,-4.252977,-2.789237,-2.799512,...,0.661526,1.149944,-0.206321,-0.355422,-1.118638,-0.935494,0,M,53,18.0
3,4,50.003367,2.003367,2227.263372,0.030303,-4.717606,-4.224721,-3.074499,-2.741106,-3.452926,...,2.255097,1.417232,2.326886,1.577574,2.142686,1.302185,0,M,52,15.0
4,5,50.334448,2.000000,2515.888944,0.030100,-3.637179,-3.890643,-3.407677,-3.308248,-3.304539,...,2.975226,2.480377,2.418446,2.309906,1.685082,1.826066,0,M,41,16.0

In [17]:
from sklearn.linear_model import LinearRegression

In [21]:
X_var= All_data[' age']
y_var= All_data['Fz_N100']